### ISSUE TITLE
使用Hox的Provider之后，tab切换失效了

### ISSUE THREAD

**Issue by suifengfengye** [umijs/hox#103]
正常情况下在page1和page2两个tab之间切换没有问题

![normal](https://github.com/umijs/hox/assets/11971670/a6fc6571-29bc-4534-b3e1-a9d88fc25380)

如果加上了AppStoreProvider包裹，tab切换就失效了，例子如下：

![exception](https://github.com/umijs/hox/assets/11971670/2e206bd2-3131-4396-8346-fba2c4bedb66)

https://codesandbox.io/s/focused-cartwright-il79d5?file=/src/App.tsx

版本如下：
"hox": "2.1.0",
"react": "18.2.0",
"react-dom": "18.2.0",

**Comment by awmleer** [comment]
@suifengfengye 非常抱歉之前 hox 存在 bug，现在这个问题已经修复掉了，我用你发的这个 codesandbox 测试了一下，2.1.1 版本已经没有这个问题了～
