### ISSUE TITLE
请问在umijs中如何使用hox？

### ISSUE THREAD

**Issue by dengxp** [umijs/hox#106]
umijs中没有入口组件文件，app.tsx只是一个运行时配置文件，如果要创建全局store，HoxRoot要放哪里？

**Comment by virtualflase** [comment]
umi/max有个useModel,那个是umi团队集成版的hox,直接参考model文件夹下面的内容试试看?

**Comment by awmleer** [comment]
如果只需要使用全局 store 的话，可以直接用 umi 的 useModel

如果想直接用 hox 的话，也可以通过在 app.tsx 中配置 `render` 来包裹 `HotRoot`～
