### ISSUE TITLE
nextjs 中使用不了

### ISSUE THREAD

**Issue by Viin-zx** [umijs/hox#11]
models/counter.js
![image](https://user-images.githubusercontent.com/19523605/69325942-f04d4180-0c85-11ea-9f65-20d3571ded21.png)

定义好后在nextjs 的 _app.js中引入直接报异常。
![image](https://user-images.githubusercontent.com/19523605/69326013-0ce97980-0c86-11ea-867f-2e3cfb0445d3.png)

![image](https://user-images.githubusercontent.com/19523605/69326061-268ac100-0c86-11ea-8819-017b9c9decc4.png)

**Comment by kenberkeley** [comment]
还有 `ReferenceError: document is not defined` ...

**Comment by awmleer** [comment]
> 还有 `ReferenceError: document is not defined` ...

`document is not defined` 的问题已经处理了，升级 hox 版本到 v1.1.0 以上即可～

**Comment by awmleer** [comment]
@Viin-zx 之前 hox 的 build target 是 es6，后来已经改成了 es5，升级一下 hox 到最新版应该就不会有这个报错了
