### ISSUE TITLE
对象解构使用剩余参数会报错

### ISSUE THREAD

**Issue by LesilyMaple** [umijs/hox#114]
![image](https://github.com/umijs/hox/assets/34186353/26a3a682-0bb7-4815-8911-dd9be7955bad)
![image](https://github.com/umijs/hox/assets/34186353/d8266b10-bd93-4415-99c4-64d2e67a52ab)
编写类似第三行这种使用对象解构剩余参数的代码就会报错，注释掉就没问题

demo见https://github.com/LesilyMaple/HoxTest

**Comment by awmleer** [comment]
这个报错看起来不像是 hox 导致的，要不你试试直接在 [pages/index.tsx](https://github.com/LesilyMaple/HoxTest/blob/main/src/pages/index.tsx) 里跑 `const {a, ...rest} = {a: 1, b: 2}` 这行代码试试看？

**Comment by LesilyMaple** [comment]
> 这个报错看起来不像是 hox 导致的，要不你试试直接在 [pages/index.tsx](https://github.com/LesilyMaple/HoxTest/blob/main/src/pages/index.tsx) 里跑 `const {a, ...rest} = {a: 1, b: 2}` 这行代码试试看？

直接在[pages/index.tsx](https://github.com/LesilyMaple/HoxTest/blob/main/src/pages/index.tsx)里跑这行代码没有问题的

**Comment by awmleer** [comment]
的确可以复现，对比了一下构建之后的 js 文件，会发现右边（也就是增加了 `const { a, ...rest } = { a: 1, b: 2 }` 之后的代码）似乎有点问题：

<img width="1472" alt="image" src="https://github.com/umijs/hox/assets/16526078/78fe28ae-78e0-4519-b2a1-1efd1faa80ca">

_createGlobalStore1 还没创建出来的时候，就在第四行被使用了

所以看起来更像是 ice 构建的问题，获取可以给他们发个 issue 问问看？或者是使用其他的框架，例如 vite next.js umi

**Comment by LesilyMaple** [comment]
> 的确可以复现，对比了一下构建之后的 js 文件，会发现右边（也就是增加了 `const { a, ...rest } = { a: 1, b: 2 }` 之后的代码）似乎有点问题：
> 
> <img alt="image" width="1472" src="https://private-user-images.githubusercontent.com/16526078/303183631-78fe28ae-78e0-4519-b2a1-1efd1faa80ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNTY5NTEsIm5iZiI6MTcwNzM1NjY1MSwicGF0aCI6Ii8xNjUyNjA3OC8zMDMxODM2MzEtNzhmZTI4YWUtNzhlMC00NTE5LWIyYTEtMWVmZDFmYWE4MGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDAxNDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNjNmNTRlMjYwMWI4MWRkYzU3ZWE3YjliZDJjOTI5MDk5NzVlNWM2NzNmMjljNjI5ZTlhOTAxYTE1MjFkNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_-vD3ExksmvVvyEf0OE168OArkDjq8DwZevw-N6DoU">
> _createGlobalStore1 还没创建出来的时候，就在第四行被使用了
> 
> 所以看起来更像是 ice 构建的问题，或许可以给他们发个 issue 问问看？或者是使用其他的框架，例如 vite next.js umi

哦哦好的 谢谢你

**Comment by awmleer** [comment]
客气啦，那 issue 我先 close 了，后面有其他问题欢迎随时再来联系
