### ISSUE TITLE
how-to-migrate-from-v1-to-v2 HotRoot is a spelling mistake

### ISSUE THREAD

**Issue by trend-allen-shao1** [umijs/hox#115]
I have found a spelling mistake in this document, which has resulted in it being unable to be found after it is imported. Please make the necessary revisions to the document promptly.
<img width="1239" alt="image" src="https://github.com/umijs/hox/assets/147225985/2a198c1c-00c5-48e0-a802-54f983f10051">

**Comment by awmleer** [comment]
Thanks for pointing out. The documentation has now been fixed.
