### ISSUE TITLE
微信小程序框架Remax中无法使用

### ISSUE THREAD

**Issue by CraxGrix** [umijs/hox#13]
`
Uncaught TypeError: Cannot read property 'createElement' of undefined
    at Object.createModel (create-model.js? [sm]:70)
    at index.js? [sm]:39
    at require (VM1309 WAService.js:19)
    at VM1309 WAService.js:19
    at index.js? [sm]:12
    at require (VM1309 WAService.js:19)
    at VM1309 WAService.js:19
    at index.js? [sm]:11
    at require (VM1309 WAService.js:19)
    at <anonymous>:8:7
`
应该是因为小程序没有createElement这个方法导致的。

**Comment by awmleer** [comment]
是[这里](https://github.com/umijs/hox/blob/b4a30b967f3495edd216835a28e6a571115e866a/src/create-model.tsx#L8)的 `document` 为 `undefined` 导致的。。因为小程序环境中是没有 document 对象的，这个问题我们正在修复～

**Comment by gankbat** [comment]
这个问题目前解决了吗？ 有其他临时解决方案嘛？

**Comment by awmleer** [comment]
v1.1.0 版本修复了这个问题～
