### ISSUE TITLE
要怎么把请求返回的数据 用hox存起来？

### ISSUE THREAD

**Issue by dream-approaching** [umijs/hox#16]
### 使用场景
用户登录之后，全局保存用户信息

### 疑问
之前都是用`dva`，请求到用户信息之后，可以在`effects`中使用`payload`将用户信息存到`redux`以供全局使用。`hox`不能带参数，那我要保存接口返回的信息要怎么做？

### 尝试
1. 我试着在createModel中暴露一个方法，接收一个参数
```js
import { useState } from 'react';
import { createModel } from 'hox';

function useTopMenuModel() {
  const [menuList, setMenuList] = useState([]);
  const saveMenuList = payload => setMenuList(payload);

  return { menuList, saveMenuList };
}

export default createModel(useTopMenuModel);

```
2. 然后在页面中调用
```js
import useTopMenuModel from '@/hox/menuModel';

const modelData = useTopMenuModel();
console.log(modelData);
modelData.saveMenuList(menuList); // menuList是接口返回的信息
```
这么做可以把menuList存起来，但是会报错  
![](https://raw.githubusercontent.com/dream-approaching/pictureMaps/master/img/20200320170121.png)

第一次用hooks，在网上也没找到相关问题，劳烦大佬们答疑下，谢谢~

**Comment by dream-approaching** [comment]
上面我那个的报错问题，我把调用方法放在useEffect里面就可以了
```js
useEffect(() => {
    modelData.saveMenuList(menuList);
}, [menuList]);
```

我参考的这个回答： https://github.com/facebook/react/issues/18147#issuecomment-592267650

那么`hox`保存全局信息就是以这种方式吗，还是说有其他更好的方式？

**Comment by brickspert** [comment]
你这样用没问题的。

不过最好把请求都直接放到 hox 中。

**Comment by dream-approaching** [comment]
> 你这样用没问题的。
> 
> 不过最好把请求都直接放到 hox 中。

感谢解答~
刚开始是想把请求放在`hox`中的，不过大多请求都带参数，文档中看到`hox`不能传参，于是就写外面了。
