### ISSUE TITLE
hox和plugin-model疑惑

### ISSUE THREAD

**Issue by ChungTak** [umijs/hox#18]
请问hox和@umijs/plugin-model 功能是不是有点重复？我们想使用简单的数据流取代dva，应该是用hox还是plugin-model呢？麻烦大神给点建议～～

**Comment by brickspert** [comment]
如果是用 umi 的话，建议用 @umijs/plugin-model

如果是其他框架的话，可以用 hox。

两个用法差不多。

**Comment by ChungTak** [comment]
明白了 谢谢 ！
