### ISSUE TITLE
与上下文 Context 以及 useContext 的配合问题

### ISSUE THREAD

**Issue by CJY0208** [umijs/hox#20]
Hello，这是一个很棒的工具！

不过由于 createModel 将容器组件创建于 root 节点之外，无法与 Context 配合食用

可否在创建 model 时指定挂载的组件？例如

```jsx

createModel(useXXX, {
  station: 'test-station'
})

<Provider>
   <HoxStation id="test-station" />
</Provider>
```

可能会产生异步问题，目前无法与 Context 协同是一个小遗憾

**Comment by awmleer** [comment]
hox 的设计思想就是“全局性”的状态管理，如果希望基于 context 做“局部”状态管理，可以参考一下 [reto](https://reto.js.org) 。。
