### ISSUE TITLE
在使用setState时会有warning

### ISSUE THREAD

**Issue by ManuRodgers** [umijs/hox#21]
![image](https://user-images.githubusercontent.com/33333844/79289919-04802c80-7f0e-11ea-9b73-3fefadf8f19d.png)

在使用setAttachments方法的时候会有如下warning：

![image](https://user-images.githubusercontent.com/33333844/79290136-a0119d00-7f0e-11ea-8a50-1213f4a86aac.png)

https://fb.me/setstate-in-render

**Comment by ManuRodgers** [comment]
I solved the issue

**Comment by GuiaLiang** [comment]
请问下是如何处理的？

**Comment by coopercoder** [comment]
> I solved the issue

我也遇到了这个问题，请教该如何解决呢
