### ISSUE TITLE
这项目不维护了么？ 还是内部已经放弃了？

### ISSUE THREAD

**Issue by X-neuron** [umijs/hox#25]
这项目不维护了么？ 还是内部已经放弃了？ 
我用 hox 搭了 纯原生的 antd webpack 的 antd design pro 的 多标签 微前端。如果放弃的话，考虑切换到其他 库中..
<img src="https://i.loli.net/2020/04/26/GmucUWpFbEZ1LC6.gif" />

**Comment by brickspert** [comment]
没放弃呀。可以继续用的。

这个项目代码很简单，一般不会出啥问题的。放心用吧。

**Comment by X-neuron** [comment]
提了个建议，好几天 没回复。还以为内部放弃了...
使用中还发现了一些问题。后续随着登录权限的制作，陆续反馈...

**Comment by awmleer** [comment]
> 提了个建议，好几天 没回复。还以为内部放弃了...
> 使用中还发现了一些问题。后续随着登录权限的制作，陆续反馈...

嗯嗯随时欢迎反馈意见哈，我们内部的一些应用也已经在使用 hox 作为数据管理方案了，可靠性不用担心的～
