### ISSUE TITLE
请问支持ssr吗？ 支持nextjs吗？  谢谢

### ISSUE THREAD

**Issue by stfenjobs** [umijs/hox#29]

**Comment by awmleer** [comment]
我们近期会做一下 SSR 的测试

**Comment by awmleer** [comment]
@stfenjobs hox 和 next.js 以及 SSR 模式都是兼容的，可以参考这个 demo 哈：[awmleer/hox-demo-with-nextjs](https://github.com/)

**Comment by stfenjobs** [comment]
@awmleer 

你好，我clone了 你发的demo，本地测试，发现似乎不是ssr模式

![image](https://user-images.githubusercontent.com/6580897/82754136-8ca2fd00-9dfd-11ea-975b-de32000e9883.png)

服务器并没有直接把123渲染到页面里， 而是 在本地把123渲染上去的

能帮忙看看吗  谢谢

**Comment by awmleer** [comment]
@stfenjobs 嗯嗯好的，我对SSR的了解也不是很深，我再去看下～

**Comment by stfenjobs** [comment]
@awmleer 

谢谢 ， 你可以问问umi项目里的同事， 他们新版支持ssr了， 他们应该懂ssr

**Comment by ycjcl868** [comment]
https://umijs.org/docs/ssr#%E6%89%A9%E5%B1%95-ctx-%E5%8F%82%E6%95%B0

扩展下 `ctx` 参数就可以了

**Comment by awmleer** [comment]
> https://umijs.org/docs/ssr#%E6%89%A9%E5%B1%95-ctx-%E5%8F%82%E6%95%B0
> 
> 扩展下 `ctx` 参数就可以了

OK～

**Comment by stfenjobs** [comment]
求支持ssr
