### ISSUE TITLE
createModel不能设置默认值

### ISSUE THREAD

**Issue by Joker0824** [umijs/hox#35]
![image](https://user-images.githubusercontent.com/26892349/83095607-4e942a80-a0d6-11ea-9e68-5d754aa9781d.png)

**Comment by awmleer** [comment]
@Joker0824 可以看下使用的 hox 版本是多少么？`createModel` 传参的这个特性是 1.1 版本才增加的

**Comment by Joker0824** [comment]
![image](https://user-images.githubusercontent.com/26892349/83109563-30d5be00-a0f4-11ea-9373-ee660835f8a1.png)

**Comment by awmleer** [comment]
@Joker0824 刚刚重发了一个补丁版 `1.1.1` 可以更新一下再试试看～

**Comment by h-a-n-a** [comment]
> @Joker0824 可以看下使用的 hox 版本是多少么？`createModel` 传参的这个特性是 1.1 版本才增加的

1.1 应该还是没有这个功能的= =，是后面加的
