### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by chenhx2015** [umijs/hox#42]
照例子写的demo，使用的是本机目录的 hox 

./src/counter.js
Module not found: Can't resolve 'hox' in '/.../hox-demo/src'

找到的解决办法: hox 的 package.json 的main 改为 lib/index.js

**Comment by awmleer** [comment]
“使用本机目录的 hox”是通过 npm link 做的么，如果是的话，可以 link `lib` 目录，因为发包的时候也是把 lib 作为根目录发布的
