### ISSUE TITLE
hook的单例性质让人费解

### ISSUE THREAD

**Issue by Crazing** [umijs/hox#44]
通过createModel包装之后的自定义hook，它竟然是个单例，更新一个使用该hook的组件，其他使用该hook的组件也会同步更新。这很奇怪，源码主要逻辑基本读懂了，只是不知道为什么这样设计，自定义hook存在的意义不就是复用逻辑吗？做成单例就很奇怪。
就像下面这样，我仅仅点击最上面的增加按钮，下面的数字同步更新了，有点违背直觉。
![图片](https://user-images.githubusercontent.com/17800062/89028391-d14b9700-d35e-11ea-87d7-152b00e1b462.png)

**Comment by mikero204** [comment]
@Crazing  我覺得你搞錯重點了 Hooks是隔離作用域的 他做成單例主要是想脫離redux store 的複雜引用 ..把他想成redux就好了

**Comment by brickspert** [comment]
hox 是为了替代 redux 的， 和你说的自定义 hooks 不一样的~
