### ISSUE TITLE
复杂类型对象的订阅更新机制

### ISSUE THREAD

**Issue by coopercoder** [umijs/hox#45]
如果更新状态时，不改变复杂类型对象地址，则不会引起订阅这个hook的其他组件的更新，是这样的吗

const useAccess = () => {
  const [access, setAccess] = useState({
    test: true,
    adminSubmit: false
  });

  // 已存在则覆盖。
  const updateAccess = (newAccess) => {
    setAccess(_.merge(access, newAccess))   // 如果不改变复杂类型对象地址，则不会引起引用这个状态的更新
  }

  return { access, updateAccess }
};

export default createModel(useAccess);

**Comment by h-a-n-a** [comment]
这个和 hox 没有关系，是 react 本身在 setState 的时候进行了浅比较，值不更新就不会驱动更新...

**Comment by awmleer** [comment]
如果需要在函数组件中使用复杂的 state 对象，可以考虑用 immer / [useSetState](https://ahooks.js.org/zh-CN/hooks/state/use-set-state) / [useSet](https://ahooks.js.org/zh-CN/hooks/state/use-set) / [useMap](https://ahooks.js.org/zh-CN/hooks/state/use-map)

**Comment by coopercoder** [comment]
> 如果需要在函数组件中使用复杂的 state 对象，可以考虑用 immer / [useSetState](https://ahooks.js.org/zh-CN/hooks/state/use-set-state) / [useSet](https://ahooks.js.org/zh-CN/hooks/state/use-set) / [useMap](https://ahooks.js.org/zh-CN/hooks/state/use-map)

谢谢 这也是个好东西，之前用redux时用过这个，不可变类型。
