### ISSUE TITLE
遇到的一个问题，或者是BUG

### ISSUE THREAD

**Issue by hellokidder** [umijs/hox#46]
![image](https://user-images.githubusercontent.com/23077808/90401320-5e694c80-e0d0-11ea-8f00-d3438e4fd6f7.png)
![image](https://user-images.githubusercontent.com/23077808/90401425-83f65600-e0d0-11ea-912e-ec14a8929d90.png)
![image](https://user-images.githubusercontent.com/23077808/90401516-9ff9f780-e0d0-11ea-92c2-085b929767de.png)
如上图所示，并没有影响到我想显示的效果但是，浏览器会弹出错误，是我的写法那里有问题？还是这是一个bug
希望能有人解答这个问题，不胜感激

**Comment by brickspert** [comment]
贴一下你的 hox 版本和 react 版本吧?

**Comment by hellokidder** [comment]
"react": "^16.13.0",
"hox": "^1.1.1",

**Comment by awmleer** [comment]
这个应该是你自己的业务逻辑问题。。
<img width="442" alt="image" src="https://user-images.githubusercontent.com/16526078/90505464-40a9ef00-e185-11ea-84a6-8785550880dc.png">
可以贴一下这两个文件么（特别是showImageInfoDrawer这个方法）

**Comment by hellokidder** [comment]
![image](https://user-images.githubusercontent.com/23077808/90510869-3dffc780-e18e-11ea-8451-b2c3160a7346.png)
![image](https://user-images.githubusercontent.com/23077808/90510997-6f789300-e18e-11ea-9018-d9f6f0df9889.png)
![image](https://user-images.githubusercontent.com/23077808/90511137-a058c800-e18e-11ea-8182-1d1f7a904117.png)

上边是imageInfoHox的代码，下边是hostImageHox的代码，因为是公司的代码所以遮盖了一部分，但是我觉得这个应该不是一个复杂的逻辑

**Comment by hellokidder** [comment]
https://github.com/facebookexperimental/Recoil/issues/12 另外这个是我查到的类似的错误

**Comment by awmleer** [comment]
出现这个 warning 的原因是就是在一个组件的**函数 body** 中（也可以理解为 render 过程中），调用了属于另一个组件的 setState，但是看上面 @hellokidder 贴的代码中，并没有找到这样的逻辑，可以考虑尝试做一个最小化的复现？

**Comment by coopercoder** [comment]
> [facebookexperimental/Recoil#12](https://github.com/facebookexperimental/Recoil/issues/12) 另外这个是我查到的类似的错误

我也遇到了你这个类似的错误提示，头疼啊

**Comment by Liuhuan247** [comment]
一模一样warning

**Comment by wwsuper** [comment]
same

**Comment by awmleer** [comment]
dd09dfe 中已修复，我发个新版本
