### ISSUE TITLE
hox 与 async await 一起用 无法更新

### ISSUE THREAD

**Issue by cnssChain** [umijs/hox#48]
componentWillMount = async() => {
    const res = await Storage.get("theme")    
    this.props.themeConfig.changeTheme( res || "light" ) 
  }

**Comment by awmleer** [comment]
这段代码也太简单了，完全看不出有啥问题。。可以考虑在 codesandbox 里复现一下

**Comment by awmleer** [comment]
似乎是和 #54 同一个问题，1.1.2 版本已修复
