### ISSUE TITLE
useCounterModel.data 相关

### ISSUE THREAD

**Issue by EiosH** [umijs/hox#53]
如果取到并调用 useCounterModel.data （ container.data ）中 setState，container.data 会改变一次，但不会触发 useModel 中的 setState，导致当前页面不会订阅 state 更新，但实际上 container.data 已经改变，所以比如跳转到有相应 model 的页面时，会拿到已经改变的数据

**Comment by awmleer** [comment]
可以给一个具体一点的例子么～

**Comment by awmleer** [comment]
Related to #54

**Comment by awmleer** [comment]
1.1.2 版本已修复
