### ISSUE TITLE
[Ques]当前采用umi的项目方案,想问同useModel的插件有什么异同?两者完成度对比

### ISSUE THREAD

**Issue by ChenYCL** [umijs/hox#58]

**Comment by wjkang** [comment]
umi-plugin-model是基于context，构建时动态在你的应用根节点之上再创建一个节点。hox是创建跟你应用根节点同级的节点。hox 是lazy的，createModel没有被调用（一般是没有进入相应的路由）就不会创建相应节点以及数据。而umi-plugin-model则是启动应用就会全部都创建

**Comment by ChenYCL** [comment]
好的 谢谢
