### ISSUE TITLE
感觉是把数据常驻内存里了，没有销毁机制，数据大了吃不消啊，不适合大型应用

### ISSUE THREAD

**Issue by daolou** [umijs/hox#67]

**Comment by brickspert** [comment]
redux 也是常驻内存的呀，我觉得这不是问题都。

**Comment by daolou** [comment]
如果仅仅是 spa 并且跑在 pc 端可能没啥大问题，但是应用在 手机端而且是多页面的，那就是资源的浪费，对手机来说这额外的负担是挺重的。

**Comment by awmleer** [comment]
@daolou 如果场景很复杂的话可以考虑用 [reto](http://reto.js.org)
