### ISSUE TITLE
大佬们，为什么要用react-reconciler自定义渲染器呢？小白求解

### ISSUE THREAD

**Issue by rayhomie** [umijs/hox#74]
源码中为什么要这样用自定义渲染器呢？

`render(
    <Executor
      onUpdate={val => {
        container.data = val;
        container.notify();
      }}
      hook={() => hook(hookArg)}
    />
  );`

**Comment by awmleer** [comment]
在大多数情况下直接用 react-dom 也是可以的，但是在小程序（remax）、ssr 等场景下，是没有 react-dom 存在的，所以基于更底层的 react-reconciler 实现一套定制化的渲染器可以做到框架无关、环境无关。
当然这套方案也并不是没有弊端的……包体积、运行时开销这些都会存在影响，未来也许我们会支持用户自己去选择渲染器，甚至在不同的环境下去使用不同的渲染器。

**Comment by rayhomie** [comment]
是不是必须要使用一种渲染器才能够执行外部传入的hook

**Comment by awmleer** [comment]
@rayhomie 是的
