### ISSUE TITLE
useCounterModel 引入问题

### ISSUE THREAD

**Issue by liubon** [umijs/hox#9]
我的react版本为16.11.0 
import { useCounterModel } from "./counter";
这种引入方式会报错，不清楚是否与react版本有关
我看到在提供的CodeSandbox中引入的方式全部为
import useUserModel from "./useUserModel";
是否意味着每一个hox模块都要单独使用一个文件

**Comment by awmleer** [comment]
可以发一下具体的报错和代码嘛？

如果你想用这种方式import：

```js
import { useCounterModel } from "./counter";
```

那你export的时候也要使用命名export的方式：

```js
export const useCounterModel = xxxxxx
```

**Comment by liubon** [comment]
其实就是实例中的 “model 之间的依赖”这部分代码，我在使用时以为与第一个实例时承接的，以为createModel(useCounter)会返回包含useXxxModel这样的属性，所以就无脑复制了，当时还好奇打印出来也没看到useXxxModel。现在看来还是理解没到位，打扰了

**Comment by awmleer** [comment]
hh好的，那我先close了～
