### ISSUE TITLE
useEffect的触发顺序

### ISSUE THREAD

**Issue by comewithl** [umijs/hox#91]
不知道这个变化算不算正常，使用了createModel封装后，useEffect的执行顺序延后了。
可以看下这个例子：https://codesandbox.io/s/nifty-pond-hv6h35?file=/src/model/test.tsx

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/16094594/172836252-2048e06f-f6fc-40e4-b16c-6d6f262e877c.png">

- version: 1.1.6

**Comment by awmleer** [comment]
看起来是预期行为的

**Comment by comewithl** [comment]
> 有点不解，加了一层model之后会致使model的Effect延后这样设计的原因是什么。

因为如果我的model的初始化执行放在useEffect中的话，这时使用model的page需要使用其暴露出来的方法（需要model初始化才能正常执行）
在这种延后情况下，就必须在增加一个ready State的判断处理。

还是说我demo中的model引入顺序有问题才导致这样的？

**Comment by awmleer** [comment]
抱歉回复的有些迟了，你发的 codesandbox 我今天看了一下，的确会有你说的这个 useEffect 顺序的问题，但是我确认了一下，这个是预期行为

model 和组件树之间的 useEffect 顺序是没有办法保证谁先谁后的，这是由于 v1 的 hox 的渲染机制导致的，v1 的 hox 是会把 model 独立渲染到另一个 React app 中，和你应用的组件树是完全独立的，如果你需要严格的确保 useEffect 顺序，可以考虑尝试一下 hox v2（目前还在 alpha 中）

**Comment by comewithl** [comment]
这是来自洪俊贤的自动回复邮件。
