### ISSUE TITLE
yarn install fails in github actions but it's ok in my local machine

### ISSUE THREAD

**Issue by lazyxu** [umijs/hox#94]
yarn install v1.22.19
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    error An unexpected error occurred: "https://registry.npmmirror.com/hox/-/hox-2.1.0.tgz: Request failed \"504 Gateway Timeout\"".
    info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/kfs/kfs/ui/yarn-error.log".

see https://github.com/lazyxu/kfs/runs/7840011080?check_suite_focus=true

**Comment by awmleer** [comment]
You are using the registry of `npmmirror`, and this seems to be a problem of `npmmirror`, not `hox`.

You can try to switch the official registry of https://registry.npmjs.org/ .
